import axios from 'axios'

export const FETCH_CHARACTER_START = "FETCH_CHARACTER_START"
export const FETCH_CHARACTER_SUCCESS = "FETCH_CHARACTER_SUCCESS"
export const FETCH_CHARACTER_FAILURE = "FETCH_CHARACTER_FAILURE"

